### ISSUE TITLE
db_connect  : permission denied when using docker image.

### ISSUE THREAD

**Issue by dgouyette** [timothepoznanski/poznote#473]
Hello, 
I'm trying to run this project for my homelab. 
To do that, i want to run it using docker. 

I tried  using `ghcr.io/timothepoznanski/poznote:1.13.3`  (1.13.4 and 1.14.0)
I run it using Komodo. 

Env variables are  : 
```
POZNOTE_USERNAME=admin
POZNOTE_PASSWORD=admin123
```

When i try to login using these credentials, i get the following error : 

```
Warning: mkdir(): Permission denied in /var/www/html/db_connect.php on line 9
Connection failed: SQLSTATE[HY000] [14] unable to open database file
```

Permission seems to be ok for the data directory : 

```bash
ls -la 
```

== 
```
drwxr-xr-x    1 www-data www-data      4096 Dec 20 15:32 css
drwxrwxr-x    1 www-data www-data      4096 Dec 20 15:33 data
-rwxr-xr-x    1 www-data www-data      8067 Dec 20 15:32 db_connect.php
```

The directory database has not been created into the data directory

**Comment by timothepoznanski** [comment]
@dgouyette 

Thanks for reporting this issue. I'm sorry you encounter this problem and hope we will find a solution.

I've pushed a change that might resolve the issue in certain environments (like Komodo). The problem seems related to creating the database directory in the mounted data volume, which can fail in some container configurations.

I've created a beta version 1.14.0**b** to test this fix.

Can you test it for me? because I cannot reproduice it myself in my environment.

Change the image in your configuration:

- image: ghcr.io/timothepoznanski/poznote:1.14.0b

If this version resolves your issue, let me know! It will help me decide whether to include this fix in the stable release.

Thanks for your feedback!

**Comment by timothepoznanski** [comment]
I have included this fix into the 1.14.2 version. Let me know if it resolved your issue please. Thanks.

**Comment by dgouyette** [comment]
Hello, thanks for the quick fix @timothepoznanski 
I tried both version 1.14.2 and 1.14.0b. 
Now a folder database is created into the data directory. 
But there is no file for sqlite. 

database folder has been created with the root user, not www-data : 
```
drwxrwxr-x    2 root     root          4096 Dec 21 07:36 database
```

And still the same error when i try to log in

**Comment by timothepoznanski** [comment]
@dgouyette

I suppose that the issue is that Docker cannot change permissions on mounted volumes in environments like Komodo.
Run this on your host machine where the data folder is located:

```
cd /path/to/your/data/folder
sudo chown -R 82:82 .
```
The UID 82 corresponds to www-data in Alpine Linux.
Then restart the container in Komodo. 

This should resolve the permission issue and allow you to log in.

Can you try and let me know please?

**Comment by dgouyette** [comment]
There is no volume attached. I used [this script](https://community-scripts.github.io/ProxmoxVE/scripts?id=komodo) to install Komodo in a LXC container (privilegied)  

I trie using portainer instead and it works... by having the same configuration. 
It works locally on my mac as well. 
I'll close this ticket. 
If you want me to run other tests don't hesitate.
Thank you for your support 🙏
